[package]
name = "seq-builder"
description = "Experimenting with macros and sequential building"
version = "0.1.0"
edition = "2021"
authors = ["mac-3"]

[lib]
proc-macro = true

[dependencies]
quote = "1.0.27"
syn = "2.0.16"
